# Generated by Django 5.0.7 on 2024-07-31 09:11

import app1.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('vid', models.CharField(default=app1.models.generate_unic_Id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,}$', message='Please enter proper first name with minimum 2 characters')])),
                ('lname', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,}$', message='Please enter proper last name with minimum 2 characters')])),
                ('gender', models.CharField(max_length=23)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=23)),
                ('state', models.CharField(max_length=23)),
                ('pincode', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[1-9]{1}[0-9]{2}[0-9]{3}$', message='Please Enter Valid 6-digit Pincode')])),
                ('dob', models.DateField()),
                ('contact', models.CharField(max_length=23, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3}[- ]?)?\\d{10}$', message='Please Enter Proper Contact Number')])),
            ],
        ),
    ]
